### ISSUE TITLE
Oracle Virtual Box needs to install a system extension that requires permissions

### ISSUE THREAD

**Issue by danlinn** [jeebak/devtools#5]
The script seems to continue, but Virtual Box doesn't get installed.

**Comment by jeebak** [comment]
@danlinn Oh, wow. I've never got a notification that this issue was opened. Sorry for not seeing this earlier.

From what I remember, there was no reliable way or a way that I'd trust, to do that from a shell script. I think this link was what I remember reading about it: https://medium.com/@DMeechan/fixing-the-installation-failed-virtualbox-error-on-mac-high-sierra-7c421362b5b5

Also, I haven't used any of the tools in this repo since around the time you submitted this issue... and in fact, I came here looking to archive this repo when I noticed this issue. Everything here is explicitly under MIT license so feel free to use and improve anything you wish!
